### ISSUE TITLE
Doesn't work due to incorrect naming

### ISSUE THREAD

**Issue by RushanM** [SmajloSlovakian/Illegal-Minecraft-translations#15]
The resource pack doesn't change the translations in the game for me. When I looked in the resource pack archive, I noticed that for some reason the language files were named in this format `ru_RU.json`, although they should be `ru_ru.json`. I renamed them and the translations worked. Please fix it.

**Comment by SmajloSlovakian** [comment]
how have i not noticed... working on it... but it might take a while

**Comment by SmajloSlovakian** [comment]
okay... it didn't take as much but it's now fixed with a workaround (every time i add a language to the project, i have to manually remap the locale with underscore of the new language to the same thing but lowercase in crowdin...)

**Comment by RushanM** [comment]
Glad to help, I really like the idea of your resource pack
